### ISSUE TITLE
Incorrect Resting Energy Display

### ISSUE THREAD

**Issue by CryptoMinerWorld** [CryptoMinerWorld/auction#35]
All gems that can store Resting Energy, now all show "Less than 5 seconds" worth of Resting Energy.

**Comment by CryptoMinerWorld** [comment]
This happens if not connected to the blockchain. Look into if this can be displayed correctly if not connected to the blockchain. If this is not a good solution then hide resting energy stats.

**Comment by joshpitzalis** [comment]
1100b745c4dad8c77d60c3e3c1dff9730c6d0528
