### ISSUE TITLE
If User is not logged on to MetaMask (or other wallet) Tell them this

### ISSUE THREAD

**Issue by CryptoMinerWorld** [CryptoMinerWorld/auction#36]
If a user clicks "Workshop" of "Buy Now" when not signed into MetaMask or another wallet the account creation window pops up. But this should not happen. Instead it should inform the user that they need to sign into a wallet to play the game, and then link them to the part of the website that explains how to do this, if they need further assistance.

**Comment by joshpitzalis** [comment]
Just finishing integrating the new tx module and then I'll get to this.

So if a user sees this new please-sign-into-a-wallet-to-play-the-game modal and is then redirected to the part of the website that explain how to do this, how do they sign up once they have a wallet?

**Comment by joshpitzalis** [comment]
How about an overlay that redirects people to download metamask or this link in game info https://cryptominerworld.com/game_info/#GameInfoMetaMask

![metamask](https://user-images.githubusercontent.com/10258114/48944155-9a976980-ef4b-11e8-96e1-b01e9c2d17e8.png)

no meta mask and it shows this, if its detects metamask then it shows the regular...

<img width="539" alt="screenshot 2018-11-23 at 6 02 15 pm" src="https://user-images.githubusercontent.com/10258114/48944172-a97e1c00-ef4b-11e8-94d2-a759abf43938.png">

**Comment by joshpitzalis** [comment]
added in 3598ed2e40e57f869f8026f362bdd0dce5650787
